### ISSUE TITLE
Refactor to be able to remove eslint-disable-line consistent-return

### ISSUE THREAD

**Issue by AndrewLane** [AndrewLane/ssh-keygen2#43]
When linting was added with https://github.com/AndrewLane/ssh-keygen2/pull/13, some undesirable

```
// eslint-disable-line consistent-return
```

comments were added to satisfy the linter.  However, it would be ideal to refactor the code to make those kludges unnecessary.

Example:

https://github.com/AndrewLane/ssh-keygen2/blob/v1.1.2/index.js#L51

**Comment by voodoods** [comment]
I tried an approach with minimal changes to satisfy the linter, please have a look.
